# Generated by Django 4.2.5 on 2023-10-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0005_alter_user_is_tnpadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnpadmin',
            name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='S_PRN',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
