# Generated by Django 4.2.5 on 2023-10-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0006_remove_tnpadmin_user_alter_student_s_prn'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='f_password',
            field=models.CharField(default='Provide a strong password', max_length=128),
        ),
        migrations.AddField(
            model_name='tnpadmin',
            name='t_password',
            field=models.CharField(default='Provide a strong password', max_length=128),
        ),
    ]
