# Generated by Django 4.2.5 on 2023-10-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0004_alter_student_diploma_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Diploma_branch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Diploma_college',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Diploma_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='Diploma_year_of_passing',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
