# Generated by Django 4.2.5 on 2023-10-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0005_alter_student_diploma_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Applcn_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Diploma_branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Diploma_college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Diploma_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Diploma_year_of_passing',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='SEM_7_sgpa',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='SEM_8_sgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
