# Generated by Django 4.2.5 on 2023-10-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0007_remove_student_applcn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='AVG_TILL_SEM_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='AVG_TILL_SEM_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
