# Generated by Django 4.2.5 on 2023-10-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0008_alter_student_avg_till_sem_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_password',
            field=models.CharField(default='default_password', max_length=128),
        ),
    ]
