# Generated by Django 4.2.5 on 2023-10-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0009_student_s_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_password',
            field=models.CharField(default='Provide a strong password', max_length=128),
        ),
    ]
