# Generated by Django 4.2.5 on 2023-10-24 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0011_student_applcn_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='content',
        ),
        migrations.AddField(
            model_name='notice',
            name='description',
            field=models.TextField(default='Type the notice related content here'),
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('CPD', 'CPD'), ('CPPA', 'CPPA')], default='define CPPA or CPD', max_length=4),
        ),
        migrations.AddField(
            model_name='notice',
            name='pdf_file',
            field=models.FileField(default='upload the file here', upload_to='notices/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='uploaded_by',
            field=models.ForeignKey(default='uploaders identity', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
