# Generated by Django 4.2.5 on 2023-10-24 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0012_remove_notice_content_notice_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='uploaded_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
