# Generated by Django 4.2.5 on 2023-10-24 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0014_alter_notice_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('CPD', 'CPD'), ('CPPA', 'CPPA')], default='CPD', max_length=4),
        ),
        migrations.AlterField(
            model_name='notice',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
