# Generated by Django 4.2.5 on 2023-10-24 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0016_rename_description_notice_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='notice',
            name='file',
            field=models.FileField(default='default_notice.pdf', upload_to='notices/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(default='Default Content'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
