# Generated by Django 4.2.5 on 2023-10-24 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0017_remove_notice_pdf_file_notice_file_notice_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='uploaded_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
