# Generated by Django 4.2.5 on 2023-10-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0004_alter_student_s_prn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_tnpadmin',
            field=models.BooleanField(default=True),
        ),
    ]
