# Generated by Django 4.2.5 on 2023-10-28 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0007_coordinator_f_password_tnpadmin_t_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='s_prn',
        ),
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.TextField(default='pending'),
        ),
        migrations.AlterField(
            model_name='application',
            name='notice_id',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to='nexus.notice'),
        ),
        migrations.AddField(
            model_name='application',
            name='S_prn',
            field=models.ForeignKey(default='20200110', on_delete=django.db.models.deletion.CASCADE, to='nexus.student'),
        ),
    ]
