# Generated by Django 4.2.5 on 2023-10-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0008_remove_application_s_prn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='XII_Percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='XII_board',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='XII_year_of_passing',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
